version: "3.7"
services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    container_name: planning-poker
    environment: 
        - ASPNETCORE_URLS=http://+:80
        - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
        - ./planning-poker:/app
    ports:
        - 8080:80
    working_dir: /app
    command: bash -c "dotnet restore && dotnet watch run --no-launch-profile"