version: "3.7"
services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    container_name: planning-poker
    environment:
        - PORT=8080
        - ASPNETCORE_URLS=http://+:8080
        - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
        - ./PlanningPoker:/app
    ports:
        - 8080:8080
    working_dir: /app
    command: bash -c "dotnet restore && dotnet watch run --no-launch-profile"